# Generated by Django 5.2.4 on 2025-08-03 21:18

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Balancete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=500)),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("dataCriacao", models.DateField(default=django.utils.timezone.now)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Balancete",
                "verbose_name_plural": "Balancetes",
                "ordering": ["-dataCriacao"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("Nome", models.CharField(max_length=500)),
                (
                    "cpf",
                    models.CharField(max_length=11, unique=True, verbose_name="CPF"),
                ),
                ("endereco", models.CharField(blank=True, max_length=1000, null=True)),
                ("dataNascimento", models.DateField()),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["Nome"],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("dataDebito", models.DateField()),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "balancete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas",
                        to="finançaPessoal.balancete",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despeza",
                "verbose_name_plural": "Despezas",
                "ordering": ["-dataDebito"],
            },
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("dataCredito", models.DateField(default=django.utils.timezone.now)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "balancete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receitas",
                        to="finançaPessoal.balancete",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
                "ordering": ["-dataCredito"],
            },
        ),
        migrations.AddField(
            model_name="balancete",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balancetes",
                to="finançaPessoal.usuario",
            ),
        ),
    ]
