# Generated by Django 5.2.4 on 2025-07-06 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finançaPessoal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancete",
            name="dataCriacao",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="receita",
            name="dataCredito",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
