# Generated by Django 5.2.4 on 2025-07-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finançaPessoal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "ordering": ["Nome"],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
