# Generated by Django 5.2.4 on 2025-07-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finançaPessoal", "0002_alter_usuario_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="dataNascimento",
        ),
    ]
